
GET http://localhost:8080/employees

###

GET http://localhost:3000/employees/67381323a79285e818c44334

###

POST http://localhost:8080/employees
Content-Type: application/json

{
    "name": "Ali",
    "role": "Customer Service Agent",
    "department": "Customer Service",
    "contactInfo": { 
        "email": "ali7823@homatil.com", "mobileNumber": "+61466713419"
    }
}

###

DELETE http://localhost:3000/employees/67381323a79285e818c44334

###

PATCH http://localhost:8080/employees/673eb70755a8e3970f50e61e
Content-Type: application/json

{
    "name": "Mysha"
}